config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"

  devise_for :users
  
  resources :projects do
    member do
      patch 'add_user'
      patch 'remove_user'
    end
  end


  
  resources :bugs do
  	member do
    	patch 'assign'
      patch 'start_working'
      patch 'work_done'
  	end
  end

  # resources :project_users, only: [:create, :destroy]

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
# frozen_string_literal: true

class Bug < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  belongs_to :project

  validates :title, :bug_type, :status, presence: true
  validates_uniqueness_of :title, scope: :project_id

  validate :screen_shot_type

  mount_uploader :screen_shot, ImageUploader

  def assign_to_name
    User.find(assign_to).name
  end

  private

  def screen_shot_type
    unless screen_shot.content_type.to_s.in?(%('image/png image/gif'))
      errors.add(:screen_shot, 'only support .png or .gif')
    end
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :project_users
  has_many :users, through: :project_users, dependent: :destroy
  has_many :bugs, dependent: :destroy

  validates :name, presence: true
end

app/models/project_user.rb
# frozen_string_literal: true

class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :bugs, foreign_key: 'creator_id'
  has_many :project_users
  has_many :projects, through: :project_users

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def manager?
    user_type == 'manager'
  end

  def qa?
    user_type == 'qa'
  end

  def developer?
    user_type == 'developer'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name user_type])
  end

  private

  def user_not_authorized
    redirect_to(request.referrer || root_path, alert: 'You are not authorized to perform this action.')
  end

  def record_not_found
    redirect_to(request.referrer || root_path, alert: 'Record Not Found')
  end
end

app/controllers/bugs_controller.rb
# frozen_string_literal: true

class BugsController < ApplicationController
  before_action :find_bug, except: %i[index new create]

  before_action :authorize_bug, except: [:index]

  def index
    authorize Bug.new(project_id: params[:project_id])
    @view_data = helpers.data_for_view Bug.where(project_id: params[:project_id])
  end

  def new
    @bug = Bug.new
    @bug.project_id = params[:project_id]
  end

  def create
    @bug = current_user.bugs.new(bug_params)
    if @bug.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @bug.update(bug_params)
      redirect_to @bug
    else
      render 'edit'
    end
  end

  def show; end

  def assign
    if @bug.update_attribute(:assign_to, current_user.id)
      redirect_to @bug, notice: 'Assigned Successfully'
    else
      redirect_to @bug, notice: 'Not Assigned'
    end
  end

  def start_working
    if @bug.update_attribute(:status, 'started')
      redirect_to @bug, notice: 'Started Successfully'
    else
      redirect_to @bug, notice: 'Not Started'
    end
  end

  def work_done
    status = @bug.bug_type == 'feature' ? 'completed' : 'resolved'
    if @bug.update_attribute(:status, status)
      redirect_to @bug, notice: 'Started Successfully'
    else
      redirect_to @bug, notice: 'Not Started'
    end
  end

  def destroy
    @bug.destroy
    redirect_to bugs_path
  end

  private

  def find_bug
    @bug ||= Bug.find(params[:id])
  end

  def bug_params
    params.require(:bug).permit(:title, :deadline, :bug_type, :status, :screen_shot, :description, :project_id)
  end

  def authorize_bug
    if @bug.present?
      authorize @bug
    else
      authorize Bug
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    redirect_to projects_url if current_user
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :find_project, except: %i[index new create]
  before_action :find_user, only: %i[add_user remove_user]
  before_action :authorize_project

  def index
    @projects = policy_scope(Project)
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.new(project_params)
    @project.created_by = current_user.id
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def show
    @pp = ProjectPresenter.new(@project, view_context)
  end

  def add_user
    if @project.users << @user
      redirect_to @project
    else
      redirect_to @project, notice: 'Can not add user to project'
    end
  end

  def remove_user
    if @project.users.destroy(@user)
      redirect_to @project
    else
      redirect_to @project, notice: 'Can not remove user from project'
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, notice: 'Project Deleted Successfully'
    else
      redirect_to projects_path, notice: 'Can not delete project'
    end
  end

  private

  def find_project
    @project ||= Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def find_user
    @user ||= User.find_by(id: params[:user_id])
  end

  def authorize_project
    if @project.present?
      authorize @project
    else
      authorize Project
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end
end

app/helpers/bugs_helper.rb
# frozen_string_literal: true

module BugsHelper
  def data_for_view(all_bugs)
    bugs = all_bugs.where(bug_type: 'bug')
    features  = all_bugs.where(bug_type: 'feature')

    view_data = {
      features: features,
      total_features: features.count,
      new_features: features.where(status: 'new').count,
      started_features: features.where(status: 'started').count,
      completed_features: features.where(status: 'completed').count,
      bugs: bugs,
      total_bugs: bugs.count,
      new_bugs: bugs.where(status: 'new').count,
      started_bugs: bugs.where(status: 'started').count,
      resolved_bugs: bugs.where(status: 'resolved').count
    }
  end
end

app/views/bugs/_form.html.erb
<%= form_for @bug do |f|%>
  <div class="form-group row">
    <%=f.label :title,'Title: ', :class=>"col-form-label col-md-1" %>
    <%=f.text_field :title , :class => 'col-md-11 form-control', :required => true %>
  </div>

  <div class="form-group row">
  	<%= f.label :deadline, 'Deadline:', :class=>"col-form-label col-md-1" %>
    <%= f.text_field :deadline, :autocomplete => 'off', :class => 'form-control col-md-5' %>
  </div>

  <div class="form-group row">
    <%= label :bug_type, 'Type: ', :class=>" col-form-label col-md-1" %>
    <div class="form-control col-md-5">  
		  <%= f.radio_button :bug_type, 'bug', :required => true %> 
		  <%= label :bug_type, 'Bug' %>
		  <%= f.radio_button :bug_type, 'feature' %> 
		  <%= label :bug_type, 'feature' %>
    </div>
      <% bug_status = ['new', 'started', 'resolved'] %>
      <%= f.label :status, 'Status:', :class=>"col-form-label col-md-1"  %>
      <%= f.select(:status, bug_status,{}, {:class => "form-control col-md-5",:required=>true}) %>
  </div>

  <div class="form-group">
    <%=f.label :screen_shot,'Screen shot:', :class=>"col-form-label" %>
    <%=f.file_field :screen_shot, :class => "form-control",:accept => "image/x-png,image/gif" %>
  </div> 

  <div class="form-group">
    <%=f.label :description , 'Description: ' %>
    <%=f.text_area :description , :class => "form-control" %>
  </div>

    <%= f.hidden_field :project_id %>
    <%= f.submit  :class => 'float-right btn btn-outline-primary'%>
<%end%>


<script type="text/javascript">
  $(document).ready(function(){
    $('#bug_deadline').datepicker({
      dateFormat: 'yy-mm-dd'
    });
  });

  $("input[name='bug[bug_type]']").change(function() {
    var obj = $("select[name='bug[status]']")[0][2]
    if(this.value==='bug'){
      obj.value = "resolved"
      obj.text  = "resolved"
    }
    else{
      obj.value = "completed"
      obj.text = "completed"
    }
  })
</script>

app/views/bugs/edit.html.erb
<div class="container">
  <h1>Edit Project</h1>
  <%= render 'form'%>
</div>

app/views/bugs/index.html.erb
<div class="container">
  <div id="collapse_wrapper">
    <div class="card">
      <a class="card-link text-white" data-toggle="collapse" href="#collapse_feature">
        <div class="card-header bg-warning">
          <div class="row">
          <h3 class="col-md-3">Features</h3>
          <div class="col-md-2 col-form-label ">Total : <span class="badge badge-light"><%=@view_data[:total_features]%></span></div>
          <div class="col-md-2 col-form-label ">New : <span class="badge badge-light"><%=@view_data[:new_features]%></span></div>
          <div class="col-md-2 col-form-label ">Started : <span class="badge badge-light"><%=@view_data[:started_features]%></span></div>
          <div class="col-md-2 col-form-label ">Completed : <span class="badge badge-light"><%=@view_data[:completed_features]%></span></div>
        </div>
        </div>
      </a>
      <div id="collapse_feature" class="collapse" data-parent="#collapse_wrapper">
        <div class="card-body">
          <table class="table">
  					<thead>
    					<tr>
      					<th scope="col">Title</th>
      					<th scope="col">Deadline</th>
                <th scope="col">Status</th>
                <th scope="col">Created By</th>
                <th scope="col">Assign To</th>
                <th scope="col">show</th>
    					</tr>
  					</thead>
  					<tbody>
    					<%@view_data[:features].each do |feature|%>
    						<tr>
      						<td><%= feature.title %></td>
      						<td><%= feature.deadline.to_date.strftime("%a, %B, %e, %Y") if feature.deadline %></td>
                  <td><%= feature.status %><%if feature.status == 'new' && feature.assign_to.nil?%><span class="spinner-grow spinner-grow-sm text-info"></span><%end%></td>
      						<td><%= feature.creator.name %></td>
      						<td><%= User.find(feature.assign_to).name if feature.assign_to %></td>
      						<td><%= link_to 'show', feature,:class=>"btn btn-outline-primary" %></td>
    						</tr>
    					<%end%>
    				</tbody>
    			</table> 
        </div>
      </div>
    </div>
    <div class="card">
      <a class="collapsed card-link text-white" data-toggle="collapse" href="#collapse_bug">
        <div class="card-header bg-danger">
          <div class="row">
            <h3 class="col-md-3">Bugs</h3>
            <div class="col-md-2 col-form-label ">Total : <span class="badge badge-light"><%=@view_data[:total_bugs]%></span></div>
            <div class="col-md-2 col-form-label ">New : <span class="badge badge-light"><%=@view_data[:new_bugs]%></span></div>
            <div class="col-md-2 col-form-label ">Started : <span class="badge badge-light"><%=@view_data[:started_bugs]%></span></div>
            <div class="col-md-2 col-form-label ">Resolved : <span class="badge badge-light"><%=@view_data[:resolved_bugs]%></span></div>
          </div>
        </div>
      </a>
      
      <div id="collapse_bug" class="collapse show" data-parent="#collapse_wrapper">
        <div class="card-body">
          <table class="table">
  					<thead>
    					<tr>
      					<th scope="col">Title</th>
      					<th scope="col">Deadline</th>
      					<th scope="col">Status</th>
      					<th scope="col">Created By</th>
      					<th scope="col">Assign To</th>
      					<th scope="col">show</th>
    					</tr>
  					</thead>
  					<tbody>
    					<%@view_data[:bugs].each do |bug|%>
    						<tr>
      						<td><%= bug.title %></td>
      						<td><%= bug.deadline.to_date.strftime("%a, %B, %e, %Y") if bug.deadline %></td>
      						<td><%= bug.status %><%if bug.status == 'new' && bug.assign_to.nil?%><span class="spinner-grow spinner-grow-sm text-info"></span><%end%></td>
      						<td><%= bug.creator.name %></td>
      						<td><%= User.find(bug.assign_to).name if bug.assign_to %></td>
      						<td><%= link_to 'show', bug,:class=>"btn btn-outline-primary" %></td>
    					  </tr>
    					<%end%>
    				</tbody>
    			</table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bugs/new.html.erb
<div class="container">
	<p class="alert"></p>
	<div class="container">
		<h2>Create a new Bug | Feature</h2>
		<hr/>
		<%= render "devise/shared/error_messages", resource: @bug %>
		<%= render 'form'%>
	</div>
</div>

app/views/bugs/show.html.erb
<%unless notice %>
	<p class="alert"></p>
<%end%>
<!-- Show bug tilte and button to change status -->
<div class="row">
	<h1 class="col-md-9"><%= @bug.title%></h1>
	<div class="col-md-3">
		<%= link_to "assign", assign_bug_path(@bug),method: :patch, :class=>"btn btn-outline-primary" unless @bug.assign_to %>
		<%if @bug.assign_to%>
			<%= link_to "Start Working", start_working_bug_path(@bug),method: :patch, :class=>"btn btn-outline-primary" if @bug.status == 'new' %>
			<%= link_to (@bug.bug_type=='bug')? 'resolved' : 'completed', work_done_bug_path(@bug),method: :patch, :class=>"btn btn-outline-primary" if @bug.status == 'started' %>
		<%end%>
	</div>
</div>
<!-- Show Description -->
<div class="row"> 
	<p class="col-md-12"><%=@bug.description%></p>
</div>

<hr>
<!-- Show Details  -->
<div class="row">
	<div class="col-md-6 black-right-border">	
		<div class="row">
			<h3 class="col-md-3">Deadline:</h3>
			<h3 class="col-md-9 text-danger"><%= @bug.deadline.to_date.strftime("%A, %B, %e, %Y") if @bug.deadline%></h3>
			<p class="col-md-3">Created at:</p>
			<p class="col-md-9"><%= @bug.created_at.to_date.strftime("%A, %B, %e, %Y")%></p>
			<p class="col-md-3">Status:</p>
			<p class="col-md-9"><%=@bug.status%></p>
			<p class="col-md-3">Created by:</p>
			<p class="col-md-9"><%=@bug.creator.name%></p>
			<p class="col-md-3">Assign to:</p>
			<p class="col-md-9"><%=@bug.assign_to_name if @bug.assign_to%></p>
			<p class="col-md-3">Project:</p>
			<p class="col-md-9"><%=@bug.project.name%></p>
		</div>
	</div>

<!-- show screen shot -->
	<div class="col-md-6">
		<img class="height-50" src="<%=@bug.screen_shot%>" data-toggle="modal" data-target="#screen_shot_modal"/> 
	</div>

</div>

<!-- Links to edit and delete -->
<div class="">
	<% if policy(:bug).edit? %>
  	<%= link_to "Edit", edit_bug_path, :class =>"btn btn-outline-warning text-primary" %>
  <%end%>
	<% if policy(:bug).destroy? %>
  	<%= link_to "Delete", @bug, :class =>"btn btn-outline-danger text-primary",
    data: { confirm: 'Are you sure?' }, method: :delete %>
	<%end%> 
</div>

<!-- Modal for screen shot-->
<div class="modal fade" id="screen_shot_modal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <img src="<%=@bug.screen_shot%>"/>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%unless notice %>
	<p class="alert"></p>
<%end%>
<p class="alert"></p>
<div class="row">
  <div class="offset-md-1 col-md-3 col-sm-0 black-right-border ">
		<%= image_tag "bug.gif" , :class=>"bug"%>
	</div>
	<div class="col-md-8 col-sm-12">	
		<div class="col-md-10 offset-md-1 center bg-light-white">
			<br>
			<h1>Welcome to Bugzilla</h1>
			<br>
			<hr/>
			<br>
			<%= link_to "sign in", new_user_session_path, :class => "btn btn-outline-primary" %>
			<hr/>
			<br>
			<%= link_to "sign up", new_user_registration_path, :class => "btn btn-outline-primary" %>
			<hr/>
			<br>
			<br>
		</div>
	</div>
</div>

app/views/layouts/_alerts.html.erb
<%if notice%>
  <p class="alert alert-info"><%= notice %></p>
<%end%>
<%if alert%>
  <p class="alert alert-info"><%= alert %></p>
<%end%>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_url%>">Bug tracking system</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path%>">
          Home <span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>
    <%= render 'layouts/sign_in' %>
  </div>
</nav>

app/views/layouts/_sign_in.html.erb
<ul class="nav navbar-nav navbar-right">
  <%if current_user%>      
    <li class="nav-item">
      <%= link_to "sign out", destroy_user_session_path, method: :delete %>
    </li>
  <%else%>
      <li class="nav-item">
        <%= link_to "sign in", new_user_session_path, id: "sign_in_btn" %> 
      </li>
      <pre> | </pre>
      <li class="nav-item"> 
        <%= link_to "sign up", new_user_registration_path, :id => "sign_up_btn" %>
      </li>  
  <%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzilla</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      
    <%= render 'layouts/nav_bar' %>
    <%= render 'layouts/alerts' %>
    
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/project_users/_add_devs_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="add_dev_modal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
    
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Add Developer to project</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      
      <!-- Modal body -->
      <div class="modal-body">

		    <ul class="list-group">
			    <% @pp.un_assigned_devs.each do |dev| %>
  			      <li class="list-group-item d-flex justify-content-between align-items-center" id="<%=dev.id%>"> <%=dev.name%>
  				      <%=@pp.link_to_add_user_to_project(dev.id)%>
  			      </li>
			    <%end%>
		    </ul>
	    </div>
      
    </div>
  </div>
</div>

app/views/project_users/_add_qas_modal.html.erb
<!-- Modal -->
  <div class="modal fade" id="add_qa_modal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Add QA to project</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
			      <ul class="list-group">
  			      <% @pp.un_assigned_qas.each do |qa| %>
    			        <li class="list-group-item d-flex justify-content-between align-items-center" id="<%=qa.id%>"> 
                    <%=qa.name%> 
    				        <%=@pp.link_to_add_user_to_project(qa.id)%>
    			        </li>
  			      <%end%>
			      </ul>
		    </div>
        
      </div>
    </div>
  </div>

app/views/projects/_form.html.erb
<%= render "devise/shared/error_messages", resource: @project %>
<%= form_for @project do |f|%>
  <%=f.label :name , :class => 'col-md-12'%>
  <%=f.text_field :name , :class => 'col-md-12' ,:required => 'true' %>
  <hr/>
  <%=f.label :description , :class => 'col-md-12' %>
  <%=f.text_area :description , :class => 'col-md-12' %>
  <hr/>
  <%= f.submit  :class => 'btn btn-primary'%>
<%end%>

app/views/projects/edit.html.erb
<div class="container">
		<h1>Edit Project</h1>
		<%= render 'form'%>
</div>

app/views/projects/index.html.erb
<%if current_user.manager?%>
  <div class="row">
    <h1 class="col-md-9"><%= current_user.name+"\'s "%>Projects</h1>
    <div class="col-md-3 col-form-label">
      <%= link_to "Create New Project", new_project_path, :class=>"btn btn-outline-primary"%>
    </div>
  </div>
  <hr/>
<%end%>
<div class="row">
  <%@projects.each do |p| %>
  	<div class="col-md-4">
  	  <div class="card">
  	      <%= link_to (current_user.manager?)? p : (current_user.qa?)? new_bug_path(:project_id=>p.id) : bugs_path(:project_id=>p.id),:class=>"btn" do%>
            <h3 class="card-header bg-info text-white"><%= p.name %></h3>
            <p class="card-body text-justify"><%= p.description %></p>
          <%end%>
        </div>
      <hr>
    </div>
  <%end%>
</div>

app/views/projects/new.html.erb
<div class="container">
	<div class="container">
		<h1>Create a new project</h1>
		<%= render 'form'%>
	</div>
</div>

app/views/projects/show.html.erb
<h1><%= @project.name%></h1>
<p><%= @project.description%></p>
<hr/>

<div class="container">
  <div class="row">
  	<%  %>
	<div class="col-md-6">
	  <div class="col-md-12 card">
	    <div class="row card-header bg-info text-white">
	      <h3 class="col-md-11">Developers 
	      	<span class="badge  badge-light"><%=@pp.project_devs_count%></span>
	      </h3>
	      <button class="col-md-1 btn btn-primary bg-light text-primary" data-toggle="modal" data-target="#add_dev_modal">+</button>
	    </div>

		  <div class="card-body">
		  	<ul class="list-group">
		  	  <% @pp.project_devs.each do |dev|%>
  					<li class="list-group-item d-flex justify-content-between align-items-center">
    			  	<p><%= dev.name %></p>
    			  	<%= @pp.link_to_delete_user_from_project(dev.id)%>
  					</li>
  			  <% end %>
  			</ul>
		  </div>
	  </div>
	</div>
	<div class="col-md-6">
	  <div class="col-md-12 card">
        <div class="row card-header bg-info text-white">
	      <h3 class="col-md-11">QA  <span class="badge  badge-light"><%=@pp.project_qas_count%></span></h3>
	      <button id="add_qa" class="col-md-1 btn btn-primary bg-light text-primary" data-toggle="modal" data-target="#add_qa_modal">+</button>
	    </div>	    
		  <div class="card-body">
		      <ul class="list-group">
		  	  <% @pp.project_qas.each do |qa|%>
  				<li class="list-group-item d-flex justify-content-between align-items-center">
    			  <p><%= qa.name %></p>
    			  <%= @pp.link_to_delete_user_from_project(qa.id)%>
  				</li>
  			  <% end %>
  			</ul>
		  </div>
	  </div>
	</div>
  </div>
</div>



<hr/>
<%= link_to "edit", edit_project_path, :class =>"btn btn-outline-primary" %> 

<%= @pp.link_to_delete_project %> 

<%= render 'project_users/add_devs_modal'%>
<%= render 'project_users/add_qas_modal'%>